import { AddNewProjectButton } from "./AddNewProject.js";
import { AddNewTaskIcon } from "./AddNewTask.js";
import { AddNewNoteIcon } from "./AddNewNote.js";
import { EditTaskDialog } from "./EditTask.js";
import { EditTodaysTasksDialog } from "./EditTodaysTasks.js";
import { Modal } from "./Modal.js";
import { CategoryDropdown } from "./CategoryDropdown.js";
import { CategoryInputPopup } from "./CategoryInputPopup.js";
import { ModalOverlay } from "./ModalOverlay.js";
import { DueDate } from "./DueDate.js";
import { CategoryContextMenu } from "./CategoryContextMenu.js";
import { PriorityDropdown } from "./PriorityDropdown.js";
import { EditNote } from "./EditNote.js";
import { TileContextMenu } from "./TileContextMenu.js";
import { ModalNoButtons } from "./ModalNoButtons.js";

customElements.define("add-new-project-button", AddNewProjectButton);
customElements.define("add-new-task-icon", AddNewTaskIcon);
customElements.define("add-new-note-icon", AddNewNoteIcon);
customElements.define("edit-task-dialog", EditTaskDialog);
customElements.define("edit-todays-tasks-dialog", EditTodaysTasksDialog);
customElements.define("modal-popup", Modal);
customElements.define("modal-no-buttons", ModalNoButtons);
customElements.define("category-dropdown", CategoryDropdown);
customElements.define("modal-overlay", ModalOverlay);
customElements.define("due-date", DueDate);
customElements.define("category-context-menu", CategoryContextMenu);
customElements.define("category-input-popup", CategoryInputPopup);
customElements.define("priority-dropdown", PriorityDropdown);
customElements.define("edit-note-dialog", EditNote);
customElements.define("tile-context-menu", TileContextMenu);
