import { AddNewProjectDialog } from "./AddNewProjectDialog__1661861941141__.js";
import { AddNewTaskDialog } from "./AddNewTaskDialog__1661861941141__.js";
import { AddNewNoteDialog } from "./AddNewNoteDialog__1661861941141__.js";
import { EditProjectDialog } from "./EditProjectDialog__1661861941141__.js";
import { EditNoteDialog } from "./EditNoteDialog__1661861941141__.js";
import { EditTaskDialog } from "./EditTaskDialog__1661861941141__.js";
import { EditTodaysTasksDialog } from "./EditTodaysTasks__1661861941141__.js";
import { Modal } from "./Modal__1661861941141__.js";
import { CategoryDropdown } from "./CategoryDropdown__1661861941141__.js";
import { CategoryInputPopup } from "./CategoryInputPopup__1661861941141__.js";
import { ModalOverlay } from "./ModalOverlay__1661861941141__.js";
import { DueDate } from "./DueDate__1661861941141__.js";
import { CategoryContextMenu } from "./CategoryContextMenu__1661861941141__.js";
import { PriorityDropdown } from "./PriorityDropdown__1661861941141__.js";
import { TileContextMenu } from "./TileContextMenu__1661861941141__.js";
import { ModalNoButtons } from "./ModalNoButtons__1661861941141__.js";
import { RichTextEditor } from "./RichTextEditor__1661861941141__.js";
import { DaysAllocatedTo } from "./DatesAllocatedTo__1661861941141__.js";

customElements.define("add-new-project-dialog", AddNewProjectDialog);
customElements.define("add-new-task-dialog", AddNewTaskDialog);
customElements.define("add-new-note-dialog", AddNewNoteDialog);
customElements.define("edit-task-dialog", EditTaskDialog);
customElements.define("edit-todays-tasks-dialog", EditTodaysTasksDialog);
customElements.define("edit-project-dialog", EditProjectDialog);
customElements.define("modal-popup", Modal);
customElements.define("modal-no-buttons", ModalNoButtons);
customElements.define("category-dropdown", CategoryDropdown);
customElements.define("modal-overlay", ModalOverlay);
customElements.define("due-date", DueDate);
customElements.define("days-allocated-to", DaysAllocatedTo);
customElements.define("category-context-menu", CategoryContextMenu);
customElements.define("category-input-popup", CategoryInputPopup);
customElements.define("priority-dropdown", PriorityDropdown);
customElements.define("edit-note-dialog", EditNoteDialog);
customElements.define("tile-context-menu", TileContextMenu);
customElements.define("rich-text-editor", RichTextEditor);
