import { AddNewProjectDialog } from "./AddNewProjectDialog__1662731128046__.js";
import { AddNewTaskDialog } from "./AddNewTaskDialog__1662731128046__.js";
import { AddNewNoteDialog } from "./AddNewNoteDialog__1662731128046__.js";
import { EditProjectDialog } from "./EditProjectDialog__1662731128046__.js";
import { EditNoteDialog } from "./EditNoteDialog__1662731128046__.js";
import { EditTaskDialog } from "./EditTaskDialog__1662731128046__.js";
import { Modal } from "./Modal__1662731128046__.js";
import { CategoryDropdown } from "./CategoryDropdown__1662731128046__.js";
import { CategoryInputPopup } from "./CategoryInputPopup__1662731128046__.js";
import { ModalOverlay } from "./ModalOverlay__1662731128046__.js";
import { DueDate } from "./DueDate__1662731128046__.js";
import { CategoryContextMenu } from "./CategoryContextMenu__1662731128046__.js";
import { PriorityDropdown } from "./PriorityDropdown__1662731128046__.js";
import { TileContextMenu } from "./TileContextMenu__1662731128046__.js";
import { ModalNoButtons } from "./ModalNoButtons__1662731128046__.js";
import { RichTextEditor } from "./RichTextEditor__1662731128046__.js";
import { DaysAllocatedTo } from "./DatesAllocatedTo__1662731128046__.js";
import { StatusDropdown } from "./StatusDropdown__1662731128046__ copy.js";

customElements.define("add-new-project-dialog", AddNewProjectDialog);
customElements.define("add-new-task-dialog", AddNewTaskDialog);
customElements.define("add-new-note-dialog", AddNewNoteDialog);
customElements.define("edit-task-dialog", EditTaskDialog);
customElements.define("edit-project-dialog", EditProjectDialog);
customElements.define("modal-popup", Modal);
customElements.define("modal-no-buttons", ModalNoButtons);
customElements.define("category-dropdown", CategoryDropdown);
customElements.define("status-dropdown", StatusDropdown);
customElements.define("modal-overlay", ModalOverlay);
customElements.define("due-date", DueDate);
customElements.define("days-allocated-to", DaysAllocatedTo);
customElements.define("category-context-menu", CategoryContextMenu);
customElements.define("category-input-popup", CategoryInputPopup);
customElements.define("priority-dropdown", PriorityDropdown);
customElements.define("edit-note-dialog", EditNoteDialog);
customElements.define("tile-context-menu", TileContextMenu);
customElements.define("rich-text-editor", RichTextEditor);
