import { AddNewProjectDialog } from "./AddNewProjectDialog.js";
import { AddNewTaskDialog } from "./AddNewTaskDialog.js";
import { AddNewNoteDialog } from "./AddNewNoteDialog.js";
import { EditProjectDialog } from "./EditProjectDialog.js";
import { EditNoteDialog } from "./EditNoteDialog.js";
import { EditTaskDialog } from "./EditTaskDialog.js";
import { EditTodaysTasksDialog } from "./EditTodaysTasks.js";
import { Modal } from "./Modal.js";
import { CategoryDropdown } from "./CategoryDropdown.js";
import { CategoryInputPopup } from "./CategoryInputPopup.js";
import { ModalOverlay } from "./ModalOverlay.js";
import { DueDate } from "./DueDate.js";
import { CategoryContextMenu } from "./CategoryContextMenu.js";
import { PriorityDropdown } from "./PriorityDropdown.js";
import { TileContextMenu } from "./TileContextMenu.js";
import { ModalNoButtons } from "./ModalNoButtons.js";
import { RichTextEditor } from "./RichTextEditor.js";
import { DaysAllocatedTo } from "./DatesAllocatedTo.js";

customElements.define("add-new-project-dialog", AddNewProjectDialog);
customElements.define("add-new-task-dialog", AddNewTaskDialog);
customElements.define("add-new-note-dialog", AddNewNoteDialog);
customElements.define("edit-task-dialog", EditTaskDialog);
customElements.define("edit-todays-tasks-dialog", EditTodaysTasksDialog);
customElements.define("edit-project-dialog", EditProjectDialog);
customElements.define("modal-popup", Modal);
customElements.define("modal-no-buttons", ModalNoButtons);
customElements.define("category-dropdown", CategoryDropdown);
customElements.define("modal-overlay", ModalOverlay);
customElements.define("due-date", DueDate);
customElements.define("days-allocated-to", DaysAllocatedTo);
customElements.define("category-context-menu", CategoryContextMenu);
customElements.define("category-input-popup", CategoryInputPopup);
customElements.define("priority-dropdown", PriorityDropdown);
customElements.define("edit-note-dialog", EditNoteDialog);
customElements.define("tile-context-menu", TileContextMenu);
customElements.define("rich-text-editor", RichTextEditor);
